import React from 'react';
import { PairingPortal } from '@/components/PairingPortal';

export const metadata = {
  title: 'Kuzmix-MD • Pairing Portal',
  description:
    'Link your WhatsApp number to Kuzmix-MD instantly with a real 8-digit pairing code generated by the Baileys Multi-Device engine.',
};

export default function StandalonePairingPage() {
  return (
    <main>
      <PairingPortal
        botName="Kuzmix-MD"
        developerName="Oni Oluwatobi"
        organization="The Kreadive Galaxy"
      />
    </main>
  );
}